### ISSUE TITLE
MILESTONE 1

### ISSUE THREAD

**Issue by ZenaMel** [Zenahr/lazystarter#15]
- [x] set up repo with venv and requirements.txt #16
- [ ] create installable python package which automatically adds our tool to the PATH of the user #17
- [x] be able to run the first command (lazystarter project-name) --> create empty directory with project-name as its name inside current root directory #18

**Comment by ZenaMel** [comment]
1/3 done!

**Comment by ZenaMel** [comment]
2/3 done!
