### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by ZenaMel** [Zenahr/lazystarter#2]
# Milestones
- [x] Get a team (1)
- [x]  Create Discord Server (2)
- [ ] MILESTONE 1 complete (7) #15 
- [ ] Define API endpoints and software design (3)
- [ ] Choose libraries for components (4)
- [ ] build out a first simple prototype and release it as a downloadable (tagged release v0.1.x) (5)
- [x] add docs (docosaurus v1.0) (6)

**Comment by ZenaMel** [comment]
(1) is done!

**Comment by ZenaMel** [comment]
(2) is done!
